version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
    - 888:80
    volumes:
    - ./FE/dist:/usr/share/nginx/html
    - ./down:/usr/share/nginx/html/down
    - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf
  php:
    image: bitnami/php-fpm:5.6-ol-7-prod
    volumes:
    - ./api:/var/www/html/api
  mysql:
    image: mysql:5.6
    ports:
    - 33060:3306
    volumes:
    - ./docker/data:/usr/data
    - ./docker/conf/my.cnf:/etc/mysql/my.cnf
    environment:
    - MYSQL_ROOT_PASSWORD=123456
